function serializeForHtml(value) {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function renderHomePage({ config, state, runtime, library, sampleGraph }) {
  const bootstrap = serializeForHtml({
    config,
    state,
    runtime,
    library,
    sampleGraph,
  });

  return [
    "<!doctype html>",
    "<html lang=\"zh-CN\">",
    "  <head>",
    "    <meta charset=\"utf-8\" />",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "    <title>NodeGraph Demo Showcase</title>",
    "    <style>",
    "      :root { color-scheme: light; --bg: #f8fafc; --ink: #0f172a; --card: rgba(255,255,255,0.9); --line: rgba(15,23,42,0.12); --accent: #2563eb; --accent2: #16a34a; }",
    "      * { box-sizing: border-box; }",
    "      body { margin: 0; min-height: 100vh; font-family: 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif; color: var(--ink); background: linear-gradient(135deg, #f8fafc, #eef6ff 58%, #f5fff8); }",
    "      main { width: min(1200px, calc(100vw - 32px)); margin: 0 auto; padding: 32px 0 48px; }",
    "      .hero, .panel { background: var(--card); border: 1px solid var(--line); border-radius: 24px; box-shadow: 0 18px 48px rgba(15,23,42,0.08); }",
    "      .hero { padding: 28px; margin-bottom: 24px; }",
    "      .badges { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }",
    "      .badge { display: inline-flex; align-items: center; border-radius: 999px; padding: 6px 12px; font-size: 12px; font-weight: 700; background: rgba(37,99,235,0.1); color: var(--accent); }",
    "      .hero h1 { margin: 0 0 12px; font-size: clamp(28px, 4vw, 42px); line-height: 1.1; }",
    "      .hero p { margin: 0; line-height: 1.7; color: rgba(15,23,42,0.8); }",
    "      .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; margin-bottom: 20px; }",
    "      .panel { padding: 20px; }",
    "      .panel h2 { margin: 0 0 8px; font-size: 20px; }",
    "      .panel p { margin: 0 0 16px; line-height: 1.6; color: rgba(15,23,42,0.78); }",
    "      .stack { display: flex; flex-direction: column; gap: 12px; }",
    "      label { display: flex; flex-direction: column; gap: 8px; font-size: 14px; font-weight: 600; }",
    "      input, select, button { font: inherit; }",
    "      input, select { width: 100%; border: 1px solid rgba(148,163,184,0.45); border-radius: 14px; padding: 12px 14px; background: rgba(255,255,255,0.96); }",
    "      .button-row { display: flex; flex-wrap: wrap; gap: 10px; }",
    "      button, a.button-link { border: none; border-radius: 14px; padding: 12px 16px; font-weight: 700; cursor: pointer; color: white; background: linear-gradient(135deg, var(--accent), #1d4ed8); text-decoration: none; }",
    "      button.secondary { background: linear-gradient(135deg, var(--accent2), #15803d); }",
    "      button.ghost { color: var(--ink); background: rgba(15,23,42,0.08); }",
    "      .meta { display: grid; gap: 10px; font-size: 13px; }",
    "      .meta strong { display: block; margin-bottom: 4px; }",
    "      pre { margin: 0; padding: 14px; border-radius: 16px; background: rgba(15,23,42,0.92); color: #e2e8f0; overflow: auto; font-size: 12px; line-height: 1.6; }",
    "      code { font-family: 'Cascadia Code', 'Fira Code', monospace; }",
    "    </style>",
    "  </head>",
    "  <body>",
    "    <main>",
    "      <section class=\"hero\">",
    "        <div class=\"badges\"><span class=\"badge\">NodeGraph Demo Client</span><span class=\"badge\">Showcase Runtime</span><span class=\"badge\">JavaScript SDK</span></div>",
    "        <h1>这个 Demo 用一套可执行的 Showcase 节点库，展示节点编辑器的字段控件、端口类型着色、连接菜单过滤，以及运行时注册、图执行、性能分析与断点调试。</h1>",
    "        <p>页面会调用内置 JavaScript SDK 运行时，先向 NodeGraph 递交节点库，再创建编辑会话；你也可以直接在本页执行示例图，或运行一个带断点的调试样例，查看 profiler 与最终输出。</p>",
    "      </section>",
    "      <section class=\"grid\">",
    "        <div class=\"panel stack\">",
    "          <div><h2>1. 创建编辑会话</h2><p>先用宿主运行时注册节点库，再向 NodeGraph 创建会话，返回真正可访问的 <code>editorUrl</code>。</p></div>",
    "          <label>节点图模式<select id=\"graphMode\"><option value=\"existing\">编辑 Showcase 示例图</option><option value=\"new\">创建空白 Showcase 图</option></select></label>",
    "          <label>节点图名称<input id=\"graphName\" value=\"Demo Showcase Pipeline\" /></label>",
    "          <div class=\"button-row\"><button id=\"createSessionButton\" type=\"button\">Create editor session</button><button id=\"forceRegisterButton\" class=\"secondary\" type=\"button\">Force refresh runtime cache</button></div>",
    "          <div class=\"meta\"><div><strong>Runtime ID</strong><span id=\"runtimeId\"></span></div><div><strong>Library Version</strong><span id=\"libraryVersion\"></span></div><div><strong>NodeGraph Base URL</strong><span id=\"nodeGraphBaseUrl\"></span></div><div><strong>Control Base URL</strong><span id=\"controlBaseUrl\"></span></div></div>",
    "          <pre id=\"sessionOutput\">No session has been created yet.</pre>",
    "          <a id=\"editorLink\" class=\"button-link\" href=\"#\" target=\"_blank\" rel=\"noreferrer\" style=\"display:none;\">Open editor page</a>",
    "        </div>",
    "        <div class=\"panel stack\">",
    "          <div><h2>2. 本地运行与调试</h2><p>使用 SDK 运行时直接执行 Showcase 图，或跑一个内置断点调试样例，结果里会包含 profiler。</p></div>",
    "          <div class=\"button-row\"><button id=\"executeGraphButton\" class=\"secondary\" type=\"button\">Run showcase graph</button><button id=\"debugGraphButton\" class=\"ghost\" type=\"button\">Run breakpoint sample</button><button id=\"refreshButton\" class=\"ghost\" type=\"button\">Refresh latest state</button></div>",
    "          <pre id=\"executionOutput\">No execution has been run yet.</pre>",
    "          <pre id=\"debugOutput\">No debug sample has been run yet.</pre>",
    "        </div>",
    "      </section>",
    "      <section class=\"grid\">",
    "        <div class=\"panel stack\">",
    "          <div><h2>3. 节点库与示例图</h2><p>这里展示的是宿主程序内置的节点库 JSON 与默认 Showcase 图，不依赖 NodeGraph 端再去拉取远端业务定义。</p></div>",
    "          <pre id=\"libraryOutput\"></pre>",
    "          <pre id=\"graphOutput\"></pre>",
    "        </div>",
    "        <div class=\"panel stack\">",
    "          <div><h2>4. 最新回调与注册</h2><p>当你在 NodeGraph 编辑页点击完成后，回调会落到 <code>/api/completed</code>；最近一次 runtime 注册信息也会显示在这里。</p></div>",
    "          <pre id=\"registrationOutput\">Runtime has not been registered yet.</pre>",
    "          <pre id=\"completionOutput\">No completion payload received yet.</pre>",
    "        </div>",
    "      </section>",
    "    </main>",
    "    <script type=\"module\">",
    "      const bootstrap = JSON.parse(document.getElementById('bootstrap').textContent);",
    "      const graphModeInput = document.getElementById('graphMode');",
    "      const graphNameInput = document.getElementById('graphName');",
    "      const sessionOutput = document.getElementById('sessionOutput');",
    "      const registrationOutput = document.getElementById('registrationOutput');",
    "      const executionOutput = document.getElementById('executionOutput');",
    "      const debugOutput = document.getElementById('debugOutput');",
    "      const completionOutput = document.getElementById('completionOutput');",
    "      const libraryOutput = document.getElementById('libraryOutput');",
    "      const graphOutput = document.getElementById('graphOutput');",
    "      const editorLink = document.getElementById('editorLink');",
    "      function pretty(value, emptyText) { return value ? JSON.stringify(value, null, 2) : emptyText; }",
    "      function applyLatest(payload) {",
    "        sessionOutput.textContent = pretty(payload.lastSession, 'No session has been created yet.');",
    "        registrationOutput.textContent = pretty(payload.lastRegistration, 'Runtime has not been registered yet.');",
    "        executionOutput.textContent = pretty(payload.lastExecution, 'No execution has been run yet.');",
    "        debugOutput.textContent = pretty(payload.lastDebug, 'No debug sample has been run yet.');",
    "        completionOutput.textContent = pretty(payload.latestCompletion, 'No completion payload received yet.');",
    "        const latestEditorUrl = payload.lastSession?.response?.editorUrl;",
    "        if (latestEditorUrl) { editorLink.href = latestEditorUrl; editorLink.style.display = 'inline-flex'; } else { editorLink.style.display = 'none'; }",
    "      }",
    "      async function loadLatest() { const response = await fetch('/api/results/latest'); applyLatest(await response.json()); }",
    "      async function postJson(path, body) { const response = await fetch(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return { response, payload: await response.json() }; }",
    "      async function forceRegister() { registrationOutput.textContent = 'Refreshing runtime cache...'; await postJson('/api/runtime/register', { force: true }); await loadLatest(); }",
    "      async function createSession() { sessionOutput.textContent = 'Creating session...'; const { response, payload } = await postJson('/api/create-session', { graphMode: graphModeInput.value, graphName: graphNameInput.value }); if (!response.ok) { sessionOutput.textContent = JSON.stringify(payload, null, 2); return; } await loadLatest(); }",
    "      async function executeGraph() { executionOutput.textContent = 'Running graph...'; await postJson('/api/runtime/execute', { graphMode: graphModeInput.value, graphName: graphNameInput.value }); await loadLatest(); }",
    "      async function debugGraph() { debugOutput.textContent = 'Running breakpoint sample...'; await postJson('/api/runtime/debug/sample', { graphMode: graphModeInput.value, graphName: graphNameInput.value }); await loadLatest(); }",
    "      document.getElementById('runtimeId').textContent = bootstrap.runtime.runtimeId;",
    "      document.getElementById('libraryVersion').textContent = bootstrap.runtime.libraryVersion;",
    "      document.getElementById('nodeGraphBaseUrl').textContent = bootstrap.config.nodeGraphBaseUrl;",
    "      document.getElementById('controlBaseUrl').textContent = bootstrap.runtime.controlBaseUrl;",
    "      libraryOutput.textContent = JSON.stringify(bootstrap.library, null, 2);",
    "      graphOutput.textContent = JSON.stringify(bootstrap.sampleGraph, null, 2);",
    "      applyLatest(bootstrap.state);",
    "      document.getElementById('createSessionButton').addEventListener('click', createSession);",
    "      document.getElementById('forceRegisterButton').addEventListener('click', forceRegister);",
    "      document.getElementById('executeGraphButton').addEventListener('click', executeGraph);",
    "      document.getElementById('debugGraphButton').addEventListener('click', debugGraph);",
    "      document.getElementById('refreshButton').addEventListener('click', loadLatest);",
    "    </script>",
    "    <script id=\"bootstrap\" type=\"application/json\">" + bootstrap + "</script>",
    "  </body>",
    "</html>",
  ].join("\\n");
}
